Repository Ashwinshankar98/TeachersPetBot, pull requests merged in 2021-11, with the labels that each got.

#30 Kailash
  src/bot.py
  src/cal.py
  src/db.py
  src/event_creation.py
  src/office_hours.py
  test/test_event_creation.py
  test/test_office_hours.py
  test/test_qna.py
  test/tests.py
  test/utils.py
Labels: bug, duplicate, invalid

#31 pylint error handling
  src/bot.py
  src/cal.py
  src/event_creation.py
  src/office_hours.py
Labels: documentation

#32 update env file variables
  .github/workflows/test.yml
Labels: documentation

#24 Added proj2rubric.md
  docs/proj2rubric.md
Labels: documentation

#35 Poll ashwin
  requirements.txt
  src/bot.py
Labels: enhancement

#42 Custom censoring
  src/bot.py
  src/profanity.py
  src/qna.py
  test/test_profanity.py
  test/tests.py
Labels: enhancement

#47 Function Descriptions file
  Functiondes.md
  docs/FunctionDescriptions
  docs/Phase1 vs Phase2
Labels: documentation

#51 Update and rename Phase1 vs Phase2 to Phase1_vs_Phase2.md
  docs/Phase1 vs Phase2
  docs/Phase1_vs_Phase2.md
Labels: documentation

#54 Help
  src/bot.py
  src/help_command.py
  test/test_help.py
  test/tests.py
Labels: enhancement

#57 Reminder Notification
  src/cal.py
Labels: enhancement

#60 Docs main
  Installation.md
  README.md
  images/attendance.png
  images/attendance_wrong_channel.png
  images/help.png
  images/help_command.png
Labels: documentation

#61 Kaushik readme
  README.md
  images/close_calls1.png
  images/close_calls2.png
  images/custom_profanity1.png
  images/custom_profanity2.png
  images/custom_profanity3.png
Labels: documentation
